.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\" http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.na
.TH J2OBJC "1" "May 2014" "j2objc" "User Commands"
.SH NAME
.B j2objc
\- translate Java source files to Objective-C
.SH SYNOPSIS
.B j2objc
[
.I options
] \fIfile1.java\fR ...
.SH DESCRIPTION
The
.B j2objc
tool translates specified Java source files into either Objective-C or
Objective-C++ sources for use in an iOS application.

.SH COMMON OPTIONS
.TP \w'\fB\-copyright\fP\fI\ nnnn\fP'u+10n
.BI \-sourcepath " path "
Specify where to find input source files
.TP
.BI \-classpath " path "
Specify where to find user class files
.TP
.BI \-d " directory "
Specify where to place generated Objective\-C files
.TP
.BI \-encoding " encoding "
Specify character encoding used by source files
.TP
.BI \-g
Generate debugging support
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Do not print status messages
.TP
\fB\-v\fR, \fB\-\-verbose
Output messages about what the translator is doing
.TP
.BI \-Werror
Make all warnings into errors
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this message.

.SH OTHER OPTIONS
.TP
\fB\-batch-translate-max\fR\=\fIn\fR
The maximum number of source files that are translated together. Batching
speeds up translation, but requires more memory.
.TP
.BI \-\-build\-closure
Translate dependent classes if out-of-date.
.TP
.BI \-\-dead\-code\-report " file "
Specify a ProGuard usage report for dead code elimination.
.TP
.BI \-\-doc\-comments
Translate Javadoc comments into Xcode-compatible comments.
.TP
.BI \-\-extract\-unsequenced
Rewrite expressions that would produce unsequenced modification errors.
.TP
.BI \-\-generate\-deprecated
Generate deprecated attributes for deprecated methods, classes, and interfaces.
.TP
.BI \-\-mapping " file "
Add a method mapping file.
.TP
.BI \-\-mem\-debug
Generate code to display memory allocation graphs.
.TP
.BI \-\-no\-class\-methods
Don't emit class methods for static Java methods.
(static methods are converted to functions)
.TP
.BI \-\-no\-final\-methods\-as\-functions
Disable generating functions for final methods.
.TP
.BI \-\-no\-hide\-private\-members
Includes private fields and methods in header file.
.TP
.BI \-\-no\-package\-directories
Generate output files to specified directory, without creating package sub-directories
.TP
.BI -pluginpath " path "
Specify where to find plugin class files
.TP
.BI \-pluginoptions " options "
Comma separated key=value pairs passed to all plugins
.TP
.BI \-\-prefix " package=prefix "
Substitute a specified prefix for a package name.
.TP
.BI \-\-prefixes " file "
Specify a properties file with prefix definitions.
.TP
.BI \-\-strip\-gwt\-incompatible
Removes methods that are marked with a GwtIncompatible
annotation, unless its value is known to be compatible.
.TP
.BI \-\-strip\-reflection
Do not generate metadata needed for Java reflection.
.TP
\fB\-\-segmented\-headers\fR
Generates headers with guards around each declared type. Useful for breaking import cycles.
.TP
\fB\-t\fR, \fB\-\-timing\-info\fR
Print time spent in translation steps.
.TP
.BI \-use\-arc
Generate Objective\-C code to support Automatic Reference Counting (ARC).
.TP
.BI \-use\-gc
Generate Objective\-C code to support garbage collection (requires
libjre_emul.a rebuild).
.TP
.BI \-use\-reference\-counting
Generate Objective\-C code to support iOS manual reference counting (default).
.TP
.BI \-x " language "
Specify what language to output.  Possible values are objective\-c (default)
and objective\-c++.
.TP
.BI \-Xbootclasspath\fR:\fIpath
Boot path used by translation (not the tool itself).
.TP
.BI \-Xno\-jsni\-warnings
Warn if JSNI (GWT) native code delimiters are used instead of OCNI delimiters.

.SH "SEE ALSO"
.BR j2objcc (1)
.PP
The full documentation for
.B j2objc
is maintained on the project site at
\fIhttp://j2objc.org/\fR.

