.\" Copyright 2012 Google Inc. All Rights Reserved.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\" http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH J2OBJCC "1" "September 2012" "j2objcc 0.5" "User Commands"
.SH NAME
.B j2objcc
\- compile translated Objective-C files
.SH SYNOPSIS
.B j2objcc
[
.I compiler-options
] \fIfile\fR ...
.SH DESCRIPTION
.B j2objcc
is a convenience script to simplify compiling Objective-C or Objective-C++
files created by \fBj2objc\fR.  It passes all options to \fBgcc\fR (or \fBclang\fR)
unchanged to the compiler.  It also includes the \fBj2objc\fR include
and library paths.
.PP
.SH "SEE ALSO"
.BR j2objc (1)
.PP
The full documentation for
.B j2objcc
is maintained on the project site at
\fIhttp://j2objc.googlecode.com/\fR.

