/* This file was generated from java/net/SocketOptions.java and is licensed
 * under the same terms. The copyright and license information for
 * java/net/SocketOptions.java follows.
 *
 * Copyright (c) 1996, 2006, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_SocketOptions */

#ifndef _Included_java_net_SocketOptions
#define _Included_java_net_SocketOptions
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_SocketOptions_TCP_NODELAY
#define java_net_SocketOptions_TCP_NODELAY 1L
#undef java_net_SocketOptions_SO_BINDADDR
#define java_net_SocketOptions_SO_BINDADDR 15L
#undef java_net_SocketOptions_SO_REUSEADDR
#define java_net_SocketOptions_SO_REUSEADDR 4L
#undef java_net_SocketOptions_SO_BROADCAST
#define java_net_SocketOptions_SO_BROADCAST 32L
#undef java_net_SocketOptions_IP_MULTICAST_IF
#define java_net_SocketOptions_IP_MULTICAST_IF 16L
#undef java_net_SocketOptions_IP_MULTICAST_IF2
#define java_net_SocketOptions_IP_MULTICAST_IF2 31L
#undef java_net_SocketOptions_IP_MULTICAST_LOOP
#define java_net_SocketOptions_IP_MULTICAST_LOOP 18L
#undef java_net_SocketOptions_IP_TOS
#define java_net_SocketOptions_IP_TOS 3L
#undef java_net_SocketOptions_SO_LINGER
#define java_net_SocketOptions_SO_LINGER 128L
#undef java_net_SocketOptions_SO_TIMEOUT
#define java_net_SocketOptions_SO_TIMEOUT 4102L
#undef java_net_SocketOptions_SO_SNDBUF
#define java_net_SocketOptions_SO_SNDBUF 4097L
#undef java_net_SocketOptions_SO_RCVBUF
#define java_net_SocketOptions_SO_RCVBUF 4098L
#undef java_net_SocketOptions_SO_KEEPALIVE
#define java_net_SocketOptions_SO_KEEPALIVE 8L
#undef java_net_SocketOptions_SO_OOBINLINE
#define java_net_SocketOptions_SO_OOBINLINE 4099L
#ifdef __cplusplus
}
#endif
#endif
