/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_UnixAsynchronousSocketChannelImpl */

#ifndef _Included_sun_nio_ch_UnixAsynchronousSocketChannelImpl
#define _Included_sun_nio_ch_UnixAsynchronousSocketChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_UNINITIALIZED
#define sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_UNINITIALIZED -1L
#undef sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_UNCONNECTED
#define sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_UNCONNECTED 0L
#undef sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_PENDING
#define sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_PENDING 1L
#undef sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_CONNECTED
#define sun_nio_ch_UnixAsynchronousSocketChannelImpl_ST_CONNECTED 2L
/*
 * Class:     sun_nio_ch_UnixAsynchronousSocketChannelImpl
 * Method:    checkConnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
