/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_UnixCopyFile */

#ifndef _Included_sun_nio_fs_UnixCopyFile
#define _Included_sun_nio_fs_UnixCopyFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_fs_UnixCopyFile
 * Method:    transfer
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_UnixCopyFile_transfer
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
