/* This file was generated from sun/nio/ch/FileChannelImpl.java and is
 * licensed under the same terms. The copyright and license information for
 * sun/nio/ch/FileChannelImpl.java follows.
 *
 * Copyright (c) 2000, 2011, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_FileChannelImpl */

#ifndef _Included_sun_nio_ch_FileChannelImpl
#define _Included_sun_nio_ch_FileChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_FileChannelImpl_MAPPED_TRANSFER_SIZE
#define sun_nio_ch_FileChannelImpl_MAPPED_TRANSFER_SIZE 8388608LL
#undef sun_nio_ch_FileChannelImpl_TRANSFER_SIZE
#define sun_nio_ch_FileChannelImpl_TRANSFER_SIZE 8192L
#undef sun_nio_ch_FileChannelImpl_MAP_RO
#define sun_nio_ch_FileChannelImpl_MAP_RO 0L
#undef sun_nio_ch_FileChannelImpl_MAP_RW
#define sun_nio_ch_FileChannelImpl_MAP_RW 1L
#undef sun_nio_ch_FileChannelImpl_MAP_PV
#define sun_nio_ch_FileChannelImpl_MAP_PV 2L
/*
 * Class:     sun_nio_ch_FileChannelImpl
 * Method:    map0
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_FileChannelImpl_map0
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     sun_nio_ch_FileChannelImpl
 * Method:    unmap0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_FileChannelImpl_unmap0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     sun_nio_ch_FileChannelImpl
 * Method:    transferTo0
 * Signature: (IJJI)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_FileChannelImpl_transferTo0
  (JNIEnv *, jobject, jint, jlong, jlong, jint);

/*
 * Class:     sun_nio_ch_FileChannelImpl
 * Method:    position0
 * Signature: (Ljava/io/FileDescriptor;J)J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_FileChannelImpl_position0
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     sun_nio_ch_FileChannelImpl
 * Method:    initIDs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_FileChannelImpl_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
