/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_UnixAsynchronousSocketChannelImpl_OpType */

#ifndef _Included_sun_nio_ch_UnixAsynchronousSocketChannelImpl_OpType
#define _Included_sun_nio_ch_UnixAsynchronousSocketChannelImpl_OpType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
