/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_UnixAsynchronousServerSocketChannelImpl */

#ifndef _Included_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl
#define _Included_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_UnixAsynchronousServerSocketChannelImpl
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_UnixAsynchronousServerSocketChannelImpl
 * Method:    accept0
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;[Ljava/net/InetSocketAddress;)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_UnixAsynchronousServerSocketChannelImpl_accept0
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
