/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_KQueuePort_Event */

#ifndef _Included_sun_nio_ch_KQueuePort_Event
#define _Included_sun_nio_ch_KQueuePort_Event
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
