/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_KQueue */

#ifndef _Included_sun_nio_ch_KQueue
#define _Included_sun_nio_ch_KQueue
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_KQueue_EVFILT_READ
#define sun_nio_ch_KQueue_EVFILT_READ -1L
#undef sun_nio_ch_KQueue_EVFILT_WRITE
#define sun_nio_ch_KQueue_EVFILT_WRITE -2L
#undef sun_nio_ch_KQueue_EV_ADD
#define sun_nio_ch_KQueue_EV_ADD 1L
#undef sun_nio_ch_KQueue_EV_ONESHOT
#define sun_nio_ch_KQueue_EV_ONESHOT 16L
#undef sun_nio_ch_KQueue_EV_CLEAR
#define sun_nio_ch_KQueue_EV_CLEAR 32L
/*
 * Class:     sun_nio_ch_KQueue
 * Method:    keventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_keventSize
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    identOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_identOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    filterOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_filterOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    flagsOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_flagsOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    kqueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_kqueue
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    keventRegister
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_keventRegister
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     sun_nio_ch_KQueue
 * Method:    keventPoll
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_KQueue_keventPoll
  (JNIEnv *, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
