/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_BsdNativeDispatcher */

#ifndef _Included_sun_nio_fs_BsdNativeDispatcher
#define _Included_sun_nio_fs_BsdNativeDispatcher
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_fs_BsdNativeDispatcher_SUPPORTS_OPENAT
#define sun_nio_fs_BsdNativeDispatcher_SUPPORTS_OPENAT 2L
#undef sun_nio_fs_BsdNativeDispatcher_SUPPORTS_FUTIMES
#define sun_nio_fs_BsdNativeDispatcher_SUPPORTS_FUTIMES 4L
#undef sun_nio_fs_BsdNativeDispatcher_SUPPORTS_BIRTHTIME
#define sun_nio_fs_BsdNativeDispatcher_SUPPORTS_BIRTHTIME 65536L
/*
 * Class:     sun_nio_fs_BsdNativeDispatcher
 * Method:    getfsstat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_fs_BsdNativeDispatcher_getfsstat
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_fs_BsdNativeDispatcher
 * Method:    fsstatEntry
 * Signature: (JLsun/nio/fs/UnixMountEntry;)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_fs_BsdNativeDispatcher_fsstatEntry
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     sun_nio_fs_BsdNativeDispatcher
 * Method:    endfsstat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_BsdNativeDispatcher_endfsstat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_nio_fs_BsdNativeDispatcher
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_BsdNativeDispatcher_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
