/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_KQueuePort */

#ifndef _Included_sun_nio_ch_KQueuePort
#define _Included_sun_nio_ch_KQueuePort
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_KQueuePort_MAX_KEVENTS_TO_POLL
#define sun_nio_ch_KQueuePort_MAX_KEVENTS_TO_POLL 512L
/*
 * Class:     sun_nio_ch_KQueuePort
 * Method:    socketpair
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_KQueuePort_socketpair
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     sun_nio_ch_KQueuePort
 * Method:    interrupt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_KQueuePort_interrupt
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_nio_ch_KQueuePort
 * Method:    drain1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_KQueuePort_drain1
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_nio_ch_KQueuePort
 * Method:    close0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_KQueuePort_close0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
