name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      MAKE_CMD: "env TRANSLATE_GLOBAL_FLAGS=--swift-friendly ENV_J2OBJC_ARCHS=macosx_iphone64 make -j32"

    steps:
      - name: java_17_env
        run: echo "JAVA_17_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV
      
      - uses: actions/checkout@v2

      # Build everything but protobuf targets, which require that the public
      # protobuf distribution be installed.
      - name: build_all
        run: $MAKE_CMD JAVA_HOME=$JAVA_17_HOME frameworks examples_dist
      
      # Test command-line tools.
      - name: test_tools
        # Disable test_jre_cycles, as cycle_finder fails on Java 17 (https://github.com/tomball/j2objc/issues/1)
        # run: $MAKE_CMD JAVA_HOME=$JAVA_17_HOME test_translator test_cycle_finder test_jre_cycles
        run: $MAKE_CMD JAVA_HOME=$JAVA_17_HOME test_translator test_cycle_finder
